### ISSUE TITLE
Add VISO

### ISSUE THREAD

**Issue by VladimirKuzlo** [keycryptovc/base#1074]

**Comment by VladimirKuzlo** [comment]
working on this

**Comment by VladimirKuzlo** [comment]
Денис ты на работу вернулся?)

пн, 6 авг. 2018 г. в 17:18, Denis Bebikh <notifications@github.com>:

**Comment by Desser** [comment]
Привет! Зашел, увидел висят, решил добавить. Сейчас в геническе на кайт-станции. На зиму присматриваю работу

**Comment by VladimirKuzlo** [comment]
А чем занимался после проекта?

пн, 6 авг. 2018 г. в 17:42, Denis Bebikh <notifications@github.com>:

**Comment by Desser** [comment]
Тогда во Вьетнаме до апреля был. Учил на кайте и переводы (англ-рус) иногда. Как у тебя, в криптосфере или в другое подался?
