### ISSUE TITLE
Try http://www.jekyllnow.com/ as a blogging tool

### ISSUE THREAD

**Issue by akhavr** [keycryptovc/base#227]

**Comment by Desser** [comment]
Second site on gh-pages may be seen as yoursite.github.io/repository name, then it is necessary to make changes in CNAME file to bind it with domain name

**Comment by Desser** [comment]
вот такой вариант нашел desser.github.io

**Comment by Desser** [comment]
или вот, лаконично организован архив, можно его как основную страницу взять https://yous.be/whiteglass/archives/

**Comment by Desser** [comment]
https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

**Comment by Desser** [comment]
http://talk.jekyllrb.com/t/second-blog-on-jekyll-in-github-pages/915?u=desser
