### ISSUE TITLE
Add CloudWithMe research 

### ISSUE THREAD

**Issue by akhavr** [keycryptovc/base#275]
Pre-ICO Project 46
Name: #Cloudwith - blockchain decentralized cloud
About: Cloudwith.me has three main objectives:

1) To decentralize the provisioning of cloud services, migrating from a global infrastructure operated by a small group of hyperscale service providers to a blockchain-based peer-to-peer infrastructure operated by millions of small individual providers and contributors of cloud resources.
2) To simplify the use of professional cloud services for all levels of web users turning such services into a commodity product universally accessible and utilized by the general public.
3) To monetize the new decentralized cloud services ecosystem with a dedicated cryptocurrency governed by a smart contract enabling automated and trusted reconciliation of payments between all peer-to-peer cloud services providers.

Site: https://token.cloudwith.me/
Pre-ICO Date:  NOW LIVE and till August, 24
ICO Date: August, 25 start
🚀Special conditions: bonus +11%🚀
Russian version: http://telegra.ph/CloudWith-08-11

**Comment by NrgDumik** [comment]
#286
