### ISSUE TITLE
Script to count number of merged PR per author

### ISSUE THREAD

**Issue by akhavr** [keycryptovc/base#333]

**Comment by NrgDumik** [comment]
https://github.com/tzachz/github-comment-counter

**Comment by Desser** [comment]
Various statistics on the pull requests in your repo. https://github.com/xiongchiamiov/github-pr-stats

**Comment by Desser** [comment]
Our latest integration, Notion for Github, solves this problem with easy-to-build Github metric dashboards. http://blog.usenotion.com/notion-for-github

**Comment by Desser** [comment]
build a custom GitHub dashboard to track your project in real-time. Build a GitHub dashboard to monitor and share your project with your team. https://www.klipfolio.com/integrations/github-dashboard

**Comment by Desser** [comment]
List pull requests merged since the last tag on the given release branch which have not yet been merged into the release branch. (Python)
https://gist.github.com/embray/4497178

**Comment by Desser** [comment]
Github API https://developer.github.com/v3/pulls/#list-pull-requests

**Comment by akhavr** [comment]
Що з цього пробували?

**Comment by Desser** [comment]
Разбираюсь с Github API

**Comment by Desser** [comment]
Merged PR for  keycryptovc/base  https://api.github.com/repos/keycryptovc/base/pulls?state=merged
shows 30 results, probably github api pagination
https://api.github.com/repos/keycryptovc/base/pulls/1 - last number corresponds to PR

**Comment by akhavr** [comment]
Ясна річ, що з github api можна написати скриптів.  Питання в тому, чи є готові

**Comment by Desser** [comment]
from aar  (https://keycryptovc.slack.com/archives/C6G1VBUEQ/p1503563711000271 )
 4.  implementation of script, working with Github API, other are beyond my possibilities, so we try to find someone experienced in python, to customize available script, or create GET script for Github API (this may take several days for because of lack of experience)

**Comment by akhavr** [comment]
What script is available?  I can do fine-tuning

**Comment by Desser** [comment]
From above variants this seem to be the most suitable https://github.com/tzachz/github-comment-counter
