### ISSUE TITLE
Create guides and templates

### ISSUE THREAD

**Issue by VladimirLevv** [keycryptovc/base#46]
a folder with 
- guide how to add new project
- people and projects template
- projects list to add

**Comment by Desser** [comment]
## Step-by-Step Guide
 1. Fork [this](https://github.com/keycryptovc/base) repository 
 2. Choose project to add from [project_list.md](projects_list.md) and mark it by *yourname (eg. "[Bitcoin] (/projects/bitcoin.md)*des")
3. Create branch in your forked repository
4. Gather and analyze info about project, fill [project template](projects_template.md), save as "yourproject.md" in created branch
5. Add your project to projects folder
6. Add link to your project in [projects.md](../projects/projects.md)
7. Create file(s) with key persons from your project, using [people template](people_template.md), save as "firstname_lastname.md"
8. Add your person(s) files to people folder
9. Add key persons to [people.md](../people/people.md)
10. Link persons with their projects
11. Pull request your branch
   View   
13  guides/people_template.md
